config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  resources :operations, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  resources :categories
  get "/about", to: "pages#about"
  get "operations/graph"
  get "/statistics", to: "statistics#index"
  get "/statistics/select_by_date", to: "statistics#select_by_date"
  get "/statistics/select_by_category", to: "statistics#select_by_category"
  get "signup", to: "users#new"
  # post "users", to: "users#create"
  resources :users, except: [:new]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get 'logout', to: "sessions#destroy"

end

app/controllers/statistics_controller.rb
class StatisticsController < ApplicationController
    before_action :require_user
    before_action :validate_dates, only: [:select_by_category, :select_by_date]

    def index
    end
  
    def select_by_category
      
      # operations = operations
      operations = current_user.operations.where(odate: start_date..end_date) if start_date && end_date
      @data = operations.data_for_reports(start_date, end_date).group("category_id").sum(:amount)
  
      operations_data = @data.transform_keys { |category| Category.find_by(id: category).name }.to_a
  
      @operations_name = operations_data.map { |e| e[0] }
      @operations_amount = operations_data.map { |e| e[1] }
      @operations = operations.order(odate: :desc)
    end
  
    def select_by_date
          
      user_operations = current_user.operations
      @current_user_operations = user_operations.where(odate: @start_date..@end_date) if @start_date && @end_date
      operations_data = user_operations.data_for_reports(@start_date, @end_date).group("odate").sum(:amount)
    
      @operations_date = operations_data.map { |key, value| key.strftime("%B %d, %Y") }
      @operations_sum = operations_data.map { |key, value| value }
    end

    private

    def validate_dates
      @start_date = params[:start_date].present? ? Date.parse(params[:start_date]) : nil
      @end_date = params[:end_date].present? ? Date.parse(params[:end_date]) : nil

      if @start_date && @end_date
        if @start_date > @end_date || @end_date > Date.today
          flash[:notice] = "Invalid date range: start date must be earlier than end date"
        end
      end
      
    end

  
    
  
end

app/helpers/statistics_helper.rb
module StatisticsHelper
  def generate_month_options(start_date, end_date)
    months = []
    (start_date..end_date).each do |date|
      months << [date.strftime("%B %Y"), date.strftime("%Y-%m")]
    end
    return months
  end

  # def doughnut_chart_data(month, category_id = nil)
  #   @categories = Category.all
  #   data = []

  #   if month.is_a?(Range)
  #     month_range = month
  #   else
  #     month_range = month.beginning_of_month..month.end_of_month
  #   end

  #   @categories.each do |category|
  #     amount = Operation.where(category_id: category_id || category.id, odate: month_range).sum(:amount)
  #     data << { label: category.name, value: amount }
  #   end

  #   return data
  # end
  
  # def gen_month_options(from, to)
  #   (from..to).map { |date| [date.strftime("%B %Y"), date.strftime("%Y-%m")] }.uniq
  # end

end

app/views/statistics/index.html.erb
<div id="page-content" class="container col-6">
  <h1>Statistics</h1>

  <div>
    <canvas id="myChart" width="600" height="400"></canvas>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
      const ctx = document.getElementById('myChart');

      const data = {
        labels: <%= raw @dates %>,
        datasets: [{
          label: 'Amount',
          data: <%= @amount %>,
          fill: false,
          borderColor: 'rgb(75, 192, 192)',
          tension: 0.1
        }]
      };

      const config = {
        type: 'line',
        data: data,
        options: {
          responsive: false
        }
      };

      const myChart = new Chart(ctx, config);
    </script>
  </div>
</div>

app/views/statistics/select_by_category.html.erb
<div id="page-content" class="container">
  <% if !logged_in? %>
      
    <h2>To see your statistics please sign up or log in</h2>
    <img src="<%= asset_path('statistics_by_category.png') %>" alt="Statistics by category">

    <%= link_to "Sign up", "/signup", class: "btn btn-primary mb-3" %>
    <%= link_to "Log in", "/login", class: "btn btn-primary mb-3" %>
      
  <% else %>
    <h2>Select by category</h2>
    <form action="<%= url_for(action: :select_by_category) %>" method="get">
      <div>
        <div class="col-md-6">
          <label class="form-label"> Select start date: </label>
          <input class="form-control" type="date" name="start_date">
        </div>
        <div class="col-md-6">
          <label class="form-label"> Select end date: </label>
          <input class="form-control" type="date" name="end_date">
        </div>
      </div>
      <div class="mt-3">
        <div class="col-md-6">
          <button type="submit" class="btn btn-primary">Show</button>
        </div>  
      </div>
    </form>
  <div class="statistics">
    <div>
      <canvas  id="myChart" class="mtChart"></canvas>
      <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
      <script>
        const ctx = document.getElementById('myChart');

        const data = {
          labels: <%=raw @operations_name %>,
          datasets: [{
            label: 'Amount',
            data: <%=raw @operations_amount %>,
            backgroundColor: [
              'rgba(255, 99, 132, 0.2)',
              'rgba(54, 162, 235, 0.2)',
              'rgba(255, 206, 86, 0.2)',
              'rgba(75, 192, 192, 0.2)',
              'rgba(153, 102, 255, 0.2)',
              'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
              'rgba(255, 99, 132, 1)',
              'rgba(54, 162, 235, 1)',
              'rgba(255, 206, 86, 1)',
              'rgba(75, 192, 192, 1)',
              'rgba(153, 102, 255, 1)',
              'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
          }]
        };

        const config = {
          type: 'doughnut',
          data: data,
          options: {
            responsive: false
          }
        };

        const myChart = new Chart(ctx, config);
      </script>
    </div>
    <div>
      <% if @operations.any? %>
        <table class="table">
          <thead>
            <tr>
              <th>Date</th>
              <th>Category</th>
              <th>Description</th>
              <th>Amount</th>
            </tr>
          </thead>
          <tbody>
            <% @operations.each do |operation| %>
              <tr>
                <td><%= operation.odate.strftime("%B %d, %Y") %></td>
                <td><%= operation.category.name %></td>
                <td><%= operation.description %></td>
                <td><%= number_to_currency(operation.amount) %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% else %>
        <p>No operations found.</p>
      <% end %>
    </div>
  </div>
  <%= link_to 'Return to operations listing', operations_path, class: "d-flex justify-content-center mt-3 text-info" %>
  <% end %>
</div>

app/views/statistics/select_by_date.html.erb
<div id="page-content" class="container col-8">
  <% if !logged_in? %>
    <h2>To see your statistics please sign up or log in</h2>
    <img src="<%= asset_path('statistics_by_date.png') %>" alt="Statistics by date">
    
    <%= link_to "Sign up", "/signup", class: "btn btn-primary mb-3" %>
    <%= link_to "Log in", "/login", class: "btn btn-primary mb-3" %>
      
  <% else %>
    <h2>All operations by dates</h2>
    <form action="<%= url_for(action: :select_by_date) %>" method="get">
      <div>
        <div class="col-md-6">
          <label class="form-label"> Select start date: </label>
          <input class="form-control" type="date" name="start_date">
        </div>
        <div class="col-md-6">
          <label class="form-label"> Select end date: </label>
          <input class="form-control" type="date" name="end_date">
        </div>
      </div>
      <div class="mt-3">
        <div class="col-md-6">
          <button type="submit" class="btn btn-primary">Show</button>
        </div>  
      </div>
    </form>
    <div class="statistics">
      <div>
        <canvas id="myChart" width="400" height="400"></canvas>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script>
          const ctx = document.getElementById('myChart');

          const data = {
            labels: <%=raw @operations_date %>,
            datasets: [{
              label: 'Amount',
              data: <%= @operations_sum %>,
              fill: false,
              borderColor: 'rgb(75, 192, 192)',
              tension: 0.1
            }]
          };

          const config = {
            type: 'line',
            data: data,
            options: {
              responsive: false
            }
          };

          const myChart = new Chart(ctx, config);
        </script>
      </div>
      <div>
        <% if @current_user_operations.present? %>
          <table class="table">
            <thead>
              <tr>
                <th>Date</th>
                <th>Category</th>
                <th>Description</th>
                <th>Amount</th>
              </tr>
            </thead>
            <tbody>
              <% @current_user_operations.each do |operation| %>
                <tr>
                  <td><%= operation.odate.strftime("%B %d, %Y") %></td>
                  <td><%= operation.category.name %></td>
                  <td><%= operation.description %></td>
                  <td><%= number_to_currency(operation.amount) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <p>No operations found.</p>
        <% end %>
      </div>
    </div>
    <%= link_to 'Return to operations listing', operations_path, class: "d-flex justify-content-center mt-3 text-info" %>
  <% end %>
</div>

app/views/statistics/stati.html.erb
<div id="page-content" class="container col-8">
  <% if !logged_in? %>
    <h2>To see your statistics please sign up or log in</h2>
    <img src="<%= asset_path('statistics_by_date.png') %>" alt="Statistics by date">
    
    <%= link_to "Sign up", "/signup", class: "btn btn-primary mb-3" %>
    <%= link_to "Log in", "/login", class: "btn btn-primary mb-3" %>
      
  <% else %>
    <h2>All operations by dates</h2>
    <form action="<%= url_for(action: :select_by_date) %>" method="get">
      <div>
        <div class="col-md-6">
          <label class="form-label"> Select start date: </label>
          <input class="form-control" type="date" name="start_date">
        </div>
        <div class="col-md-6">
          <label class="form-label"> Select end date: </label>
          <input class="form-control" type="date" name="end_date">
        </div>
      </div>
      <div class="mt-3">
        <div class="col-md-6">
          <button type="submit" class="btn btn-primary">Show</button>
        </div>  
      </div>
    </form>
    <div class="statistics">
      <div>
        <canvas id="myChart" width="400" height="400"></canvas>
        <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
        <script>
          const ctx = document.getElementById('myChart');

          const data = {
            labels: <%=raw @operations_date %>,
            datasets: [{
              label: 'Amount',
              data: <%= @operations_sum %>,
              fill: false,
              borderColor: 'rgb(75, 192, 192)',
              tension: 0.1
            }]
          };

          const config = {
            type: 'line',
            data: data,
            options: {
              responsive: false
            }
          };

          const myChart = new Chart(ctx, config);
        </script>
      </div>
      <div>
        <% if @current_user_operations.present? %>
          <table class="table">
            <thead>
              <tr>
                <th>Date</th>
                <th>Category</th>
                <th>Description</th>
                <th>Amount</th>
              </tr>
            </thead>
            <tbody>
              <% @current_user_operations.each do |operation| %>
                <tr>
                  <td><%= operation.odate.strftime("%B %d, %Y") %></td>
                  <td><%= operation.category.name %></td>
                  <td><%= operation.description %></td>
                  <td><%= number_to_currency(operation.amount) %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <p>No operations found.</p>
        <% end %>
      </div>
    </div>
    <%= link_to 'Return to operations listing', operations_path, class: "d-flex justify-content-center mt-3 text-info" %>
  <% end %>
</div>

app/views/statistics/statistics.html.erb
<h1>Statistics</h1>

<%= form_tag(statistics_operations_path, method: :get) do %>
  <div class="form-group">
    <%= label_tag(:start_date, "Start date:") %>
    <%= date_field_tag(:start_date, @start_date) %>
  </div>

  <div class="form-group">
    <%= label_tag(:end_date, "End date:") %>
    <%= date_field_tag(:end_date, @end_date) %>
  </div>

  <div class="form-group">
    <%= label_tag(:category_id, "Category:") %>
    <%= select_tag(:category_id, options_from_collection_for_select(@categories, :id, :name)) %>
  </div>

  <%= submit_tag("Get statistics", class: "btn btn-primary") %>
<% end %>

<div class="row">
  <div class="col-md-6">
    <h2>Total amount:</h2>
    <p><%= number_to_currency(@total_amount) %></p>
  </div>

  <div class="col-md-6">
    <h2>Operations by year:</h2>
    <%= column_chart @grouped_by_year, height: "400px" %>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <h2>Operations by month:</h2>
    <%= column_chart @grouped_by_month, height: "400px" %>
  </div>

  <div class="col-md-6">
    <h2>Operations by day:</h2>
    <%= column_chart @grouped_by_day, height: "400px" %>
  </div>
</div>