config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  resources :operations, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  resources :categories
  get "/about", to: "pages#about"
  get "operations/graph"
  get "/statistics", to: "statistics#index"
  get "/statistics/select_by_date", to: "statistics#select_by_date"
  get "/statistics/select_by_category", to: "statistics#select_by_category"
  get "signup", to: "users#new"
  # post "users", to: "users#create"
  resources :users, except: [:new]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get 'logout', to: "sessions#destroy"

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :operations

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :require_user
  def show
    
  end

  def index
    @categories = Category.all
  end

  def edit
    
  end

  def new
    @category = Category.new
  end
   
  def create
    @category = Category.new(category_params)

    if @category.save
      flash[:notice] = "Category was seccessfully created."
      redirect_to @category
    else
      render "new"
    end 
  end

  def update
    
    if @category.update(category_params)
      flash[:notice] = "Category was successfully updated."
      redirect_to @category
    else
      render "edit"
    end
  end

  def destroy
    @category.destroy
    flash[:notice] = "Category was successfully deleted."
    redirect_to categories_url 
  end
  
  private

  def set_category
    @category = Category.find(params[:id])
  end

  def category_params
    params.require(:category).permit(:name, :description)
  end

end

app/views/categories/_form.html.erb
<div class="row justify-content-center rounded">
    <div class="col-10">
      <%= form_with(model: @category, local: true) do |form| %>
        <% if @category.errors.any? %>
          <div class="alerts" id="error_explanation">
            <h2 class="alerts-heading"><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
            <ul>
            <% @category.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>
        <div class="form-group mb-3 row">
          <%= form.label :name %>
          <%= form.text_field :name, class: 'col-2 form-control', placeholder:"Name of category" %>
        </div>
        <div class="form-group mb-3 row">
          <%= form.label :description %>
          <%= form.text_area :description, class: 'col-2 form-control', placeholder:"Description of category" %>
        </div>
        <div class="actions action_btn mb-3">
          <%= form.submit class: 'btn btn-info' %>
        </div>
      <% end %>      
    </div>    
  </div>

app/views/categories/edit.html.erb
<div id="page-content" class="container col-6">
  <h2>Edit Category</h2>  
  <%= render "form" %>
  <%= link_to "Cancel and return to categories listing", categories_path, class: "d-flex justify-content-center mt-3 text-info" %>
</div>

app/views/categories/index.html.erb
<%= stylesheet_link_tag 'category_show' %>
<div id="page-content" class="container col-6">
    <h1>Categories</h1>

    <%# <p><%= link_to "Create New Category", new_category_path, class: "btn btn-primary"</p> %>

    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @categories.each do |category| %>
          <tr>
            <td><%= category.name %></td>
            <td><%= category.description %></td>
            <td>
            <div class="d-flex justify-content gap-3">
              <%= link_to "View", category_path(category), class: "btn btn-info" %>
              <%= link_to "Edit", edit_category_path(category), class: "btn btn-warning" %>
              <%= button_to "Delete", category_path(category), method: :delete, onclick: "return confirm('Are you sure?')", class: "btn btn-danger" %>
            </div> 
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= link_to "Create new Category", new_category_path, class: "btn btn-info"%>

</div>

app/views/categories/new.html.erb
<div id="page-content" class="container">
  <h2>New Category</h2>  
  <%= render "form" %>
  <%= link_to 'Cancel and return to categories listing', categories_path, class: "d-flex justify-content-center mt-3 text-info" %>
</div>    

app/views/categories/show.html.erb
<%= stylesheet_link_tag 'category_show' %>


<div id="page-content" class="container col-6">
  <h3>Category <%= @category.name %></h3>
  <p><%= @category.description %></p>
  

    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <th>Actions</th>        
        </tr>
      </thead>
      <tbody>
        <tr>
            <td><%= @category.name %></td>
            <td><%= @category.description %></td>
            
            <td>
              <div class="d-flex justify-content gap-3">
                <%= link_to "Edit", edit_category_path(@category), class: "btn btn-warning" %>
                
                <%= button_to "Delete", category_path(@category), method: :delete, onclick: "return confirm('Are you sure?')", class: "btn btn-danger" %>
              </div>
            </td> 
          
          </tr>
        
      </tbody>
    </table>
  

  <%# <%= link_to "Back", categories_path, class: "btn btn-secondary" %> 
  <%= link_to 'Return to categories listing', categories_path, class: "btn btn-info" %>
</div>

  