config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  resources :operations, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  resources :categories
  get "/about", to: "pages#about"
  get "operations/graph"
  get "/statistics", to: "statistics#index"
  get "/statistics/select_by_date", to: "statistics#select_by_date"
  get "/statistics/select_by_category", to: "statistics#select_by_category"
  get "signup", to: "users#new"
  # post "users", to: "users#create"
  resources :users, except: [:new]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get 'logout', to: "sessions#destroy"

end

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white-50">
  <div class="container text-center">
    <small>Copyright &copy; <%= link_to "DadaLV GitHub", "https://github.com/DadaLV", class: "text-white-50" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
 <div class="container alerts-heading">
      <% flash.each do |name, msg| %>
      <div class="alerts alert alert-<%= name == "notice" ? "success" : "danger" %> alert-dismissible fade show" role="alert">
        <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      <% end %>
    </div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "MyFM", root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "About", "/about", class: "nav-link active" %>
        </li>
        <% if !logged_in? %>
          <li class="nav-item">
            <%= link_to "Sign up", "/signup", class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Add operation", new_operation_path, class: "nav-link" %>
          </li>
        <% end %>
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Statistics
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Statistics by category", "/statistics/select_by_category", class: "nav-link" %></li>            
              <li><%= link_to "Statistics by date", "/statistics/select_by_date", class: "nav-link" %></li>
            </ul>
          </li>
        <% end %>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User
          </a>
          <ul class="dropdown-menu">
            <% if logged_in? %>
                <li><%= link_to current_user.username, user_path(current_user), class: "nav-link" %></li>
                <li><%= link_to "Edit your profile", edit_user_path(current_user), class: "dropdown-item" %></li>
                <li><%= button_to "Delete your profile", user_path(current_user), class: "dropdown-item text-danger", method: :delete, onclick: "return confirm('Are you sure? All your operations will be deleted as well')" %></li>            
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "Log out", "/logout", class: "nav-link", data: { turbo_method: :delete } %></li>
            <% else %>
                <li><%= link_to "Log in", "/login", class: "nav-link" %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceApp</title>
    <%= favicon_link_tag 'favicon.ico' %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_importmap_tags %>

    
  </head>

  <body>
    
    <%= render "layouts/navigation" %>
    <%= render "layouts/messages" %>
    <%= yield %>
    <%= render "layouts/footer" %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>