config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  resources :operations, only: [:show, :index, :new, :create, :edit, :update, :destroy]
  resources :categories
  get "/about", to: "pages#about"
  get "operations/graph"
  get "/statistics", to: "statistics#index"
  get "/statistics/select_by_date", to: "statistics#select_by_date"
  get "/statistics/select_by_category", to: "statistics#select_by_category"
  get "signup", to: "users#new"
  # post "users", to: "users#create"
  resources :users, except: [:new]
  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  get 'logout', to: "sessions#destroy"

end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :category
  belongs_to :user

  validates :amount, presence: true, numericality: { greater_than: 0 }
  validates :odate, presence: true
  validates :description, presence: true, length: { minimum: 3, maximum: 100 }

  scope :data_for_reports, -> (start_date, end_date) {
    operations = where(odate: start_date..end_date)
    operations
  }

end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index]
  before_action :require_same_user, only: [:show, :edit, :update, :destroy]

  
  def index
    redirect_to user_path(current_user) if logged_in?
    @operations = Operation.paginate(page: params[:page], per_page: 7)
    # @operations = Operation.order(:odate)
    # operations_data = Operation.all.map { |op| [op.odate.strftime("%B %d, %Y"), op.amount.to_s] }
    # operations_data_sorted = operations_data.sort

    # @dates = operations_data_sorted.map { |e| e[0] }
    # @amount = operations_data_sorted.map { |e| e[1].to_i }
    # @dates = ["1", "2", "3", "4", "5"]
    # @amount = [10, 20, 30, 40, 0]
    
  end

  def show
    
  end

  def new
    @operation = Operation.new
  end

  def create
    @operation = Operation.new(operation_params)
    @operation.user = current_user
    if @operation.save
      flash[:notice] = "Operation was seccessfully created."
      redirect_to @operation
    else
      render :new
    end
  end

  def edit
    
  end

  def update
    if @operation.update(operation_params)
      flash[:notice] = "Operation was successfully updated."
      redirect_to @operation 
    else
      render "edit"
    end
  end

  def destroy
    @operation.destroy
    flash[:notice] = "Operation was successfully deleted"
    redirect_to operations_url
  end

  private

  def set_operation
    @operation = Operation.find(params[:id])
  end

  def operation_params
    params.require(:operation).permit(:description, :amount, :odate, :category_id)
  end

  def require_same_user
    if current_user != @operation.user
      flash[:alert] = "You can operate only with your own operation"
      redirect_to root_path
    end
  end

end

app/views/operations/_form.html.erb
<%= form_with model: @operation do |form| %>
  <%= render "shared/error_messages", obj: @operation %>

  <div class="form-group">
    <%= form.label Date %>
    <%= form.datetime_local_field :odate, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name, {prompt: "Select a category"}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :amount %>
    <%= form.number_field :amount, class: "form-control", step: "0.01" %>
  </div>

  <%# <div class="form-group">
    <%= form.label :notes %>
    <%# <%= form.text_area :notes, class: "form-control" %> 
  <%# </div> %> 

  <div class="actions">
    <%= form.submit "Create", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/operations/_graph.html.erb
      <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
      <canvas id="myChart" width="600" height="400"></canvas>
      <script>
        const ctx = document.getElementById('myChart').getContext('2d');
        
        

        const data = {
            labels: <%= raw @dates %>,
            datasets: [{
              label: 'Amount',
              data: <%= @amount %>,
              fill: false,
              borderColor: 'rgb(75, 192, 192)',
              tension: 0.1
            }]
          };

        const config = {
          type: 'line',
          data: data,
          options: {
            responsive: false
          }
        };
        const myChart = new Chart(ctx, config);
      </script>
  

app/views/operations/_operation.html.erb
<% if !logged_in? %>
    
  <h2>To see your operations please sign up or log in</h2>
  <%= link_to "Sign up", "/signup", class: "btn btn-primary mb-3" %>
  <%= link_to "Log in", "/login", class: "btn btn-primary mb-3" %>
    
<% else %>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Amount</th>
        <th>Date</th>
        <th>Category</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @operations.each do |operation| %>
        <% if logged_in? && operation.user == current_user %>
        <tr>
          <td><%= operation.description %></td>
          <td><%= operation.amount %></td>
          <td><%= operation.odate.strftime("%B %d, %Y %I:%M %p") %></td>
          <td><%= operation.category.name %></td>
          <td>
            <div class="d-flex justify-content gap-3">
              <%= link_to "Show", operation_path(operation), class: "btn btn-info mr-2" %>
              <%= link_to "Edit", edit_operation_path(operation), class: "btn btn-warning mr-2" %>
              <%= button_to "Delete", operation_path(operation), method: :delete, onclick: "return confirm('Are you sure?')", class: "btn btn-danger" %>
            </div>
          </td>
        </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>
<%# <% else %>
  <%# <h2>To see your operations please sign up or log in</h2> %>
<% end %>

app/views/operations/edit.html.erb
<div id="page-content" class="container col-6">
  <h2>Edit Operation</h2>  
  <%= render "form" %>
  <%= link_to "Cancel and return to operations listing", operations_path, class: "d-flex justify-content-center mt-3 text-info" %>
</div>

app/views/operations/index.html.erb
<%= stylesheet_link_tag 'category_show' %>
<div id="page-content" class="container col-6">
  
  <h1>Operations</h1>
  <% if logged_in? %>
    <%= link_to "Create New Operation", new_operation_path, class: "btn btn-info mb-3" %> 
  <% end %>
  <div class="apple_pagination">
    <%= will_paginate @operations, :container => false %>
  </div>
  <%= render "operation" %>
  <div class="apple_pagination">
    <%= will_paginate @operations, :container => false %>
  </div>
  <% if logged_in? %>
    <%= link_to "Show statistics by month", "/statistics/select_by_category", class: "btn btn-primary mb-3" %>
    <%= link_to "Show statistics by category", "/statistics/select_by_date", class: "btn btn-primary mb-3" %>
    <%# <%= render "graph" %> 
  <% end %>
</div>

app/views/operations/new.html.erb
<div id="page-content" class="container col-6">
  <h2>New Operation</h2>  
  <%= form_with model: @operation do |form| %>
  <%= render "shared/error_messages", obj: @operation %>
  

  <div class="form-group">
    <%= form.label Date %>
    <%= form.datetime_local_field :odate, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name, {prompt: "Select a category"}, class: "form-control" %>
  </div>
  
  <div>
    <%= link_to "Create new Category", new_category_path, class: "mt-2 mb-2 btn btn-info"%>
  </div>

  <div class="form-group">
    <%= form.label :description %>
    <%= form.text_field :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :amount %>
    <%= form.number_field :amount, class: "form-control", step: "0.01" %>
  </div>

  <%# <div class="form-group">
    <%= form.label :notes %>
    <%# <%= form.text_area :notes, class: "form-control" %> 
  <%# </div> %> 

  <div class="actions">
    <%= form.submit "Create", class: "btn btn-primary" %>
  </div>
<% end %>
  <%= link_to 'Cancel and return to operations listing', operations_path, class: "d-flex justify-content-center mt-3 text-info" %>
</div>

app/views/operations/show.html.erb
<%= stylesheet_link_tag 'category_show' %>


<div id="page-content" class="container col-6">
  <h3>Operation <%= @operation.description %></h3>
  <p><%= @operation.category.name %></p>
  

    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Amount</th>
          <th>Date</th>
          <th>Category</th>
          <th>Actions</th>        
        </tr>
      </thead>
      <tbody>
        <tr>
            <td><%= @operation.description %></td>
            <td><%= @operation.amount %></td>
            <td><%= @operation.odate.strftime("%B %d, %Y %I:%M %p") %></td>
            <td><%= @operation.category.name %></td>
            
            <td>
              <div class="d-flex justify-content gap-3">
                <%= link_to "Edit", edit_operation_path(@operation), class: "btn btn-warning" %>
                
                <%= button_to "Delete", operation_path(@operation), method: :delete, onclick: "return confirm('Are you sure?')", class: "btn btn-danger" %>
              </div>
            </td> 
          
          </tr>
        
      </tbody>
    </table>
  

  <%# <%= link_to "Back", categories_path, class: "btn btn-secondary" %> 
  <%= link_to "Return to operations listing", operations_path, class: "btn btn-info" %>
</div>